export const FETCH_USERS_REQUEST= 'FETCH_USERS_REQUEST' 
export const FETCH_USERS_SUCCESS= 'FETCH_USERS_SUCCESS' 
export const FETCH_USERS_FAILURE= 'FETCH_USERS_FAILURE' 

export const MAKE_POST_REQUEST ='MAKE_POST_REQUEST'
export const MAKE_POST_SUCCESS = 'MAKE_POST_SUCCESS'
export const MAKE_POST_FAILURE = 'MAKE_POST_FAILURE'